#!/usr/bin/env python3
"""KiCad auto-placement for Buck Converter"""

import sys, pcbnew

W = pcbnew.FromMM(50)
H = pcbnew.FromMM(40)

b = pcbnew.BOARD()
ol = pcbnew.PCB_SHAPE()
ol.SetShape(pcbnew.SHAPE_T_RECT)
ol.SetLayer(pcbnew.Edge_Cuts)
ol.SetStart(pcbnew.VECTOR2I(0,0))
ol.SetEnd(pcbnew.VECTOR2I(W,H))
b.Add(ol)

f=pcbnew.FootprintLoad("","Capacitor_SMD:C_1206_3216Metric")
if f:f.SetReference("C1");f.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(5.0),pcbnew.FromMM(12.0)));b.Add(f)
else:print("Missing:Capacitor_SMD:C_1206_3216Metric")
f=pcbnew.FootprintLoad("","Package_DIP:DIP-8_W7.62mm")
if f:f.SetReference("U1");f.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(15.0),pcbnew.FromMM(8.0)));b.Add(f)
else:print("Missing:Package_DIP:DIP-8_W7.62mm")
f=pcbnew.FootprintLoad("","Package_TO_THT:TO-220-3_Vertical")
if f:f.SetReference("Q1");f.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(15.0),pcbnew.FromMM(20.0)));b.Add(f)
else:print("Missing:Package_TO_THT:TO-220-3_Vertical")
f=pcbnew.FootprintLoad("","Inductor_SMD:L_CD54")
if f:f.SetReference("L1");f.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(30.0),pcbnew.FromMM(20.0)));b.Add(f)
else:print("Missing:Inductor_SMD:L_CD54")
f=pcbnew.FootprintLoad("","Diode_SMD:D_SMA")
if f:f.SetReference("D1");f.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(30.0),pcbnew.FromMM(28.0)));b.Add(f)
else:print("Missing:Diode_SMD:D_SMA")
f=pcbnew.FootprintLoad("","Capacitor_SMD:C_1206_3216Metric")
if f:f.SetReference("C2");f.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(40.0),pcbnew.FromMM(12.0)));b.Add(f)
else:print("Missing:Capacitor_SMD:C_1206_3216Metric")
f=pcbnew.FootprintLoad("","Resistor_SMD:R_0805_2012Metric")
if f:f.SetReference("R1");f.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(15.0),pcbnew.FromMM(32.0)));b.Add(f)
else:print("Missing:Resistor_SMD:R_0805_2012Metric")
f=pcbnew.FootprintLoad("","Resistor_SMD:R_0805_2012Metric")
if f:f.SetReference("R2");f.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(15.0),pcbnew.FromMM(36.0)));b.Add(f)
else:print("Missing:Resistor_SMD:R_0805_2012Metric")
f=pcbnew.FootprintLoad("","Connector_PinHeader_2.54mm:PinHeader_2x5_P2.54mm_Vertical")
if f:f.SetReference("J1");f.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(5.0),pcbnew.FromMM(28.0)));b.Add(f)
else:print("Missing:Connector_PinHeader_2.54mm:PinHeader_2x5_P2.54mm_Vertical")
f=pcbnew.FootprintLoad("","Connector_PinHeader_2.54mm:PinHeader_2x5_P2.54mm_Vertical")
if f:f.SetReference("J2");f.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(45.0),pcbnew.FromMM(28.0)));f.SetOrientationDegrees(90);b.Add(f)
else:print("Missing:Connector_PinHeader_2.54mm:PinHeader_2x5_P2.54mm_Vertical")

b.Save("auto_placed.kicad_pcb")
print("[OK] Saved. Open in KiCad PCB Editor -> Route -> Auto-route")
